name: Production

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    
  deploy:
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      AWS_ROLE_ARN: arn:aws:iam::766373560006:role/OrganizationAccountAccessRole
    secrets: inherit